version: '2'
services:
  install:
    image: jmfirth/webpack
    command: npm rebuild -q
    volumes:
      - .:/app
    tty: true

  build:
    image: jmfirth/webpack
    command: webpack
    volumes:
      - .:/app
    tty: true
  
  watch:
    image: jmfirth/webpack
    command: webpack-dev-server --hot --inline --progress --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:8080"
    tty: true
